# Generated by Django 3.2 on 2022-01-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=10)),
                ('car_friendly_name', models.CharField(max_length=254)),
                ('car_model', models.CharField(max_length=254)),
                ('car_pax', models.DecimalField(decimal_places=0, max_digits=1)),
                ('car_class', models.CharField(max_length=254)),
                ('car_premium', models.DecimalField(decimal_places=0, max_digits=3)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=254)),
                ('tour_friendly_name', models.CharField(max_length=254)),
                ('tour_description', models.TextField()),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tour_distance', models.CharField(max_length=7)),
                ('tour_duration', models.CharField(max_length=7)),
                ('tour_ranking', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tour_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tour_isspecialoffer', models.BooleanField()),
                ('tour_specialoffer', models.CharField(blank=True, max_length=100, null=True)),
                ('tour_specialoffer_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('tour_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.city')),
                ('tour_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.CharField(max_length=24)),
                ('review_order_id', models.CharField(max_length=6)),
                ('review_order_date', models.CharField(max_length=24)),
                ('review_customer_id', models.CharField(max_length=84)),
                ('review_ranking', models.DecimalField(decimal_places=2, max_digits=2)),
                ('review_text', models.TextField()),
                ('review_tour_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour')),
            ],
        ),
    ]
