# Generated by Django 3.2 on 2022-01-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20220116_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_order_date',
            field=models.DateField(),
        ),
    ]
