# Generated by Django 3.2 on 2022-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_review_review_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_premium',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
