# Generated by Django 3.2 on 2022-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20220113_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_ranking',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
